name: Robot Framework - Regressivo

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Execute tests
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        # browser: 'firefox'
        # robot_threads: 2
        robot_tests_dir: Tests
        robot_reports_dir: reports

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: reports
        path: reports

  generate_report:
    if: always()
    needs: [test] 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download reports
      uses: actions/download-artifact@v4
      with:
        name: reports
    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2.5
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: GitHub Pages v3
      uses: peaceiris/actions-github-pages@v3.1.12
        
            